### ISSUE TITLE
Uncompleted steps should not have alpha according to Material Doc

### ISSUE THREAD

**Issue by WonderCsabo** [ernestoyaquello/vertical-stepper-form#10]
Uncompleted steps should not have alpha, but the title should stay the same, and the circle should be gray:

![screen shot 2016-07-27 at 17 58 26](https://cloud.githubusercontent.com/assets/480485/17182466/e1eee314-5423-11e6-8c05-9f9f62859094.png)

**Comment by ernestoyaquello** [comment]
Sorry for the inconvenience, but in this library I decided to use alpha for disabled elements instead of a grey color because I personally think that it looks better:

![compare](https://cloud.githubusercontent.com/assets/2463287/17183456/74142790-541f-11e6-8155-dbea32bc7423.jpg)

As I explained in another issue, it was never my intention to follow all the official specifications precisely, but just approximately. Anyway, feel free to modify the library until it fits all the requirements of your app! :)
