### ISSUE TITLE
How do I listen to click events on the "continue" buttons?

### ISSUE THREAD

**Issue by vinaybn92** [ernestoyaquello/vertical-stepper-form#25]
A reference to the button itself would allow me to handle click events and also enable/disable the button. Also, how do you change the text on the confirmation button?

**Comment by ernestoyaquello** [comment]
As you can see in the code of the [example project](https://github.com/ernestoyaquello/vertical-stepper-form/tree/master/app/src/main/java/verticalstepperform/ernestoyaquello/com/verticalstepperform), you can activate or deactivate those buttons by setting the steps as completed or uncompleted. In addition, as also shown in the sample code, the only thing that you have to do in order to change the text of the confirmation button is to override the string ```vertical_form_stepper_form_confirm_button``` in the resources of your app.

About having a reference to the buttons, I do not see why it would be useful. What do you need the reference for exactly? Maybe there are good reasons to include that feature, but right now I don't really see any, so I don't think I am including it in the next version of the library. In any case, if you are really interested on it, you can always extend the library and override the method ```createStepLayout``` in order to get and store the references to the buttons. These are the kind of things why I set all the methods as protected! :)

**Comment by ahmadalibaloch** [comment]
I have forms on different steps. Now I need to do some calculations when a form is complete, and user presses `continue` button, and then confirm from user the results of that calculations. This must happen when the user presses Continue button. Right now its not possible. I tried accessing the previous form `stepNumber `of the `OnStepOpening(int stepNumber)` parameter, but its not reliable because user can go to any step without continue button in that case there could be problems of giving user wrong step number calculation and null pointer exceptions if first step is opening. 

SO------- here I think we need a new event `OnContinue(int StepNumber)` step number here is the step number of continue button.
