### ISSUE TITLE
Empty EditText Field

### ISSUE THREAD

**Issue by juliettegonzalez** [ernestoyaquello/vertical-stepper-form#26]
I have implemented your vertical stepper form but I have one issue that I can definitely not solve : my EditText created on the steps of createStepContentView() are always empty. 
Anytime, it's impossible to access to the value, even thought through a textWatcher I can have the value input. 
I followed exactly what you describe on your project, that's why I have now no more idea about the origin of that problem.. 
I hope you can help! 
[CreateInterventionActivity.txt](https://github.com/ernestoyaquello/vertical-stepper-form/files/412998/CreateInterventionActivity.txt)

**Comment by ernestoyaquello** [comment]
I don't know exactly what you are planning to achieve here. You are creating three different EditText views, but every time that you create one you store a reference to it in the class variable "name", which means that this variable will only have a reference to the last EditText view that you have created, but not to the other ones. Therefore, when you check the name on ```checkName()```, you are actually checking the last EditText view (which is probably empty) instead of the first one.

I am going to close this issue because those are problems of your implementation, not of the library. J'espère que tu pourras améliorer ton code pour réussir à le faire fonctionner :)

**Comment by juliettegonzalez** [comment]
My bad! Horrible mistake, now it's obvious! Sorry about that! 
Merci, la librairie est top en tout cas! Tout fonctionne à merveille :)
