### ISSUE TITLE
Vertical line should appear between collapsed steps as well

### ISSUE THREAD

**Issue by WonderCsabo** [ernestoyaquello/vertical-stepper-form#9]
![screen shot 2016-07-27 at 17 54 51](https://cloud.githubusercontent.com/assets/480485/17182289/452270a0-5423-11e6-91be-494d99d85495.png)

**Comment by ernestoyaquello** [comment]
In my opinion, it is a waste of space. Mobile devices have small screens, so it is more useful not to show these lines when steps are collapsed. Thus, I am afraid that I will not change how these lines look. Anyway, feel free to copy and modify my code as you wish :)

![compare](https://cloud.githubusercontent.com/assets/2463287/17183528/d1918cbe-541f-11e6-8ad8-0f2d7b9e7797.jpg)

By the way, to avoid any confusion, it is important to point out that my library doesn't follow Material Design guidelines completely, because it was never my intention to implement the vertical stepper forms looking exactly like the examples created by Google, but just really similar. I apologize for the misunderstanding (I will clarify this point in the readme file).

**Comment by WonderCsabo** [comment]
Uh, i already opened several issues regarding material design doc. 😕

**Comment by ernestoyaquello** [comment]
I am really sorry, I should have clarified this before. Anyway, I am very grateful for your help and I will consider some of your suggestions. Thanks!

**Comment by WonderCsabo** [comment]
Anyway, i think you should implement the material design look, because that is what most people will look for. If you do not like the sizes of the material design, you can make those things configurable (not necessary via the builder, you can also achieve it with resources like you do with the translation).
I think creating a library which almost looks like the material guidelines are very confusing and a missed opportunity whether you add this to the readme or not.

BTW, thanks for creating this library, it is great already!

**Comment by ernestoyaquello** [comment]
That is a good point as well as a great suggestion. I will try to do so in the future, but I don't really know if I will have time to work on this library as much as I would like (right now I am very busy). Thanks again!

**Comment by WonderCsabo** [comment]
@ernestoyaquello to be clear: i would gladly open pull requests for all the issues i opened during the next few days as i intend to include this library on a project i am working on.

**Comment by ernestoyaquello** [comment]
Feel free to do it! I cannot guarantee that I will include them all, but any help will be appreciated, that's for sure.
